### ISSUE TITLE
기본 사이트 레이아웃 디자인

### ISSUE THREAD

**Issue by cometkim** [cometkim/blog-src#4]

**Comment by CometKim** [comment]
레이아웃이 무거우면 하위 페이지나 템플릿에서 커스텀이 어려워지기 때문에 최대한 간결하게 유지할 것.

현 시점에서 필요한 건 `<head>` 태그 기본 내용하고 사이트 헤더 컴포넌트 정도인 듯.

**Comment by cometkim** [comment]
Gatsby 레이아웃 컴포넌트는 일단 이쯤에서 정리.
