### ISSUE TITLE
기본 페이지

### ISSUE THREAD

**Issue by cometkim** [cometkim/blog-src#7]
- [x] Home(index) 페이지
- [x] 블로그 포스트 기본 템플릿
- [x] 404 페이지

**Comment by CometKim** [comment]
첫 페이지(index)에 필요한 내용 여기 전부 정리

**Comment by CometKim** [comment]
브런치, 미디엄 참고
* 사이트 헤더: Title, Logo, Home Link 는 기본적으로 필요함
* 프로필 카드: 블로그 주인장에 대한 요약. 프로필 사진, 풀네임, 소셜 계정 등
* 글 목록 (최신 순):
  * 글 제목 (링크)
  * 게시일
  * 게시자
  * 태그
  * 요약
  * Read More... (역시 링크)

**Comment by CometKim** [comment]
> 프로필 카드: 블로그 주인장에 대한 요약. 프로필 사진, 풀네임, 소셜 계정 등

별도 컴포넌트로 만들면 될 듯. 사실 [Gravatar](https://www.gravatar.com/) 쪽에서 소스를 땡겨받는게 더 나을 것 같지만, 현재는 author가 한 명이므로 일단 정적인 정보를 넣도록 하자.

**Comment by CometKim** [comment]
아무리 생각해도 Gravatar 쓰는게 좋을 것 같아서 이슈 추가 #10

**Comment by CometKim** [comment]
게시물 속성 중에 게시자, 게시일 부분은 커밋 기준으로 들어가게끔 자동화하고 싶다.

접근 방법이 다양할 것 같으므로 이슈 추가

**Comment by CometKim** [comment]
글 목록의 미리보기는 `excerpt` 필드로 쿼리 가능. 없는 필드는 일단 author에 넣는 것으로 하면 다음 쿼리로 될 것같다.

```gql
query IndexQuery {
    allMarkdownRemark {
        edges {
            node {
                excerpt
                frontmatter {
                    path
                    title
                    author
                    tags
                }
            }
        }
    }
}
```

**Comment by CometKim** [comment]
테스트 포스트 몇 개 넣으면 대략 이렇게 나옴

![image](https://user-images.githubusercontent.com/9696352/36063849-8d463e94-0ec5-11e8-9c96-170fd865a4da.png)

**Comment by CometKim** [comment]
Author랑 Tag 는 페이지가 없으니 아직 링크 아님

**Comment by cometkim** [comment]
404 페이지 까지 완료
